### ISSUE TITLE
Installing asciidoc-assistant dependencies... stays forever but does not install packages

### ISSUE THREAD

**Issue by hilsonp** [asciidoctor/atom-asciidoc-assistant#17]
I installed the asciidoc-assistant using the package manager from within Atom.
I also tried installing it with "apm install asciidoc-assistant".
Both way succeed (ie: the package gets installed).
Nevertheless, none of the 4 asciidoc packages get installed (language-asciidoc, asciidoc-preview, autocomplete-asciidoc, asciidoc-image-helper).

Atom gives a nice notification "Installing asciidoc-assistant dependencies" but nothing seems to happen.

What can I provide as information/log to help troubleshoot this ?
![image](https://user-images.githubusercontent.com/7338241/49501307-d519d400-f872-11e8-8a0d-b00fbfc21798.png)

**Comment by tcowan** [comment]
I had this problem as well, and I worked around it by installing the four packages individually.

**Comment by Tejeev** [comment]
Same.  Seems a broken package to me

**Comment by Tejeev** [comment]
Atom 1.34.0 on Xubuntu 18.04

**Comment by ldez** [comment]
I will try to fix that as soon as possible, sorry.

**Comment by Eonm** [comment]
@ldez  Updating  "atom-package-deps": "~4.0.1" to  "atom-package-deps": "~5.0.0" in package.json fixed the problem for me.

**Comment by ldez** [comment]
Fixed by v0.2.3
