### ISSUE TITLE
TOC

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/atom-asciidoc-assistant#19]
It will be very useful to have clickable TOC somewhere on the sidebar, like here: https://atom.io/packages/structure-view

**Comment by mojavelinux** [comment]
Why not just use structure view? That's what I tend to use myself.

**Comment by john-cj** [comment]
Yes, you are correct - there is no need to duplicate entities.

Since I wasn't able to install Structure View for some reason, I found [document-outline](https://atom.io/packages/document-outline). Works great. Additional features:

* Folding
* It shows where you are

Also, here is [weboutline](https://github.com/LennyN95/weboutline). Doesn't have such features and doesn't work for AsciiDoctor (Markdown only), but have interesting idea with quick search filter.

**Comment by john-cj** [comment]
So, I will close it.
