### ISSUE TITLE
Add atom-asciidoc-image-helper package to this grouping

### ISSUE THREAD

**Issue by chuckf** [asciidoctor/atom-asciidoc-assistant#3]
As this seems to be a roll-up package of useful Atom packages for Asciidoc, I suggest adding the [atom-asciidoc-image-helper](https://github.com/asciidoctor/atom-asciidoc-image-helper) package to the grouping.

**Comment by bwklein** [comment]
This makes sense.

**Comment by ldez** [comment]
Al ready done! See v0.2.0! :tada:
