### ISSUE TITLE
chore: continuous delivery

### ISSUE THREAD

**Issue by ldez** [asciidoctor/atom-asciidoc-assistant#5]
- [x] generated encrypted SSH key
- [x] add Atom Token to Travis UI
- [x] uncomment `.travis.yml`
- [x] change env variable in `.travis/publish.sh`
- [x] add the SSH key to Github :wink: 

@mojavelinux same players play again :smile:

**Comment by ldez** [comment]
ping @mojavelinux

**Comment by mojavelinux** [comment]
Oops, I wasn't watching this repository. I'm on it!

**Comment by mojavelinux** [comment]
The publish script failed because it says the tag commit is behind. Not sure what the problem is.

https://travis-ci.org/asciidoctor/atom-asciidoc-assistant/jobs/143532106

**Comment by ldez** [comment]
I have made a mistake with the repository url:
`GIT_REPOSITORY="git@github.com:asciidoctor/atom-autocomplete-asciidoc.git"`
instead of 
`GIT_REPOSITORY="git@github.com:asciidoctor/atom-asciidoc-assistant.git"`

Now it's fixed: https://github.com/asciidoctor/atom-asciidoc-assistant/commit/c04686564d3386b5b3ad8c713c56a1eb13adc29f

**Comment by mojavelinux** [comment]
Ah, good catch!
